cmd_vel:
  topic: cmd_vel
  fields:
  - velocity_x
  - velocity_y
  - velocity_z

uas_odom:
  topic: uas_odom
  fields:
  - position_x
  - position_y
  - position_z

velocity:
  topic: velocity
  fields: null

blash:
  topic: velocity
  fields: 'vector_x'
